# Generated by Django 3.0.8 on 2020-07-08 14:19

from django.db import migrations, models
import mailer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive', models.FileField(storage=mailer.models.MyFileSystemStorage(), upload_to='mailer/archive')),
                ('archive_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MailJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(max_length=1000)),
                ('to', models.CharField(max_length=200)),
                ('attachment', models.ManyToManyField(to='mailer.Archive')),
            ],
        ),
    ]
