# Generated by Django 3.0.8 on 2020-07-22 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mailer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive', models.FileField(storage=mailer.models.MyFileSystemStorage(), upload_to='mailer/archive')),
                ('archive_name', models.CharField(max_length=200)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MailJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(max_length=1000)),
                ('to', models.CharField(max_length=200)),
                ('executed_on', models.CharField(max_length=200)),
                ('executed_at', models.TimeField()),
                ('status', models.CharField(max_length=200)),
                ('attachment', models.ManyToManyField(blank=True, to='mailer.Archive')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
