# Generated by Django 3.0.8 on 2020-07-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcontent',
            name='task_name',
            field=models.CharField(default='weekly report', max_length=200),
            preserve_default=False,
        ),
    ]
