# Generated by Django 3.0.8 on 2020-07-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailjob',
            name='creator',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
