# Generated by Django 3.0.8 on 2020-07-15 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0003_auto_20200715_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailjob',
            name='creator',
        ),
    ]
