# Generated by Django 3.0.8 on 2020-07-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0003_auto_20200703_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcontent',
            name='attachment',
            field=models.FileField(upload_to='mailer/upload_files'),
        ),
    ]
