# Generated by Django 3.0.8 on 2020-07-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0004_auto_20200706_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcontent',
            name='attachment',
            field=models.FileField(upload_to='files'),
        ),
    ]
