# Generated by Django 3.0.8 on 2020-07-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0005_auto_20200706_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcontent',
            name='body',
            field=models.TextField(max_length=1000),
        ),
    ]
