# Generated by Django 3.0.8 on 2020-07-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0007_auto_20200706_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcontent',
            name='attachment',
            field=models.FileField(upload_to='attachments'),
        ),
    ]
