# Generated by Django 3.0.8 on 2020-07-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0008_auto_20200706_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcontent',
            name='attachment',
            field=models.FileField(blank=True, upload_to='attachments'),
        ),
    ]
