# Generated by Django 3.0.8 on 2020-07-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0009_auto_20200706_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.FileField(upload_to='library')),
            ],
        ),
        migrations.AddField(
            model_name='emailcontent',
            name='favbook',
            field=models.ManyToManyField(to='mailer.Library'),
        ),
    ]
