# Generated by Django 3.0.8 on 2020-07-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0010_auto_20200706_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='name',
            field=models.CharField(default='book1', max_length=200),
            preserve_default=False,
        ),
    ]
