# Generated by Django 3.0.8 on 2020-07-07 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0011_library_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcontent',
            name='favbook',
        ),
        migrations.RemoveField(
            model_name='emailcontent',
            name='attachment',
        ),
        migrations.AddField(
            model_name='emailcontent',
            name='attachment',
            field=models.ManyToManyField(to='mailer.Library'),
        ),
    ]
