# Generated by Django 3.0.8 on 2020-07-07 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0012_auto_20200707_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='name',
        ),
    ]
