# Generated by Django 3.0.8 on 2020-07-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0015_auto_20200707_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='file_name',
            field=models.CharField(default='shit', max_length=200),
            preserve_default=False,
        ),
    ]
